@url_dev = http://localhost:3055/v1/api

###signUp
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop Tips",
    "email": "shoptipjs04@gmail.com",
    "password": "123456"
}